#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MapSharp.SourceGenerator;

[Generator]
public class MapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with MapFrom or MapTo attributes
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Generate the mapping code
        context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration &&
               classDeclaration.AttributeLists.Count > 0;
    }

    private static ClassToGenerate? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
            return null;

        var mapFromAttributes = new List<INamedTypeSymbol>();
        var mapToAttributes = new List<INamedTypeSymbol>();

        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name == "MapFromAttribute" &&
                attribute.ConstructorArguments.Length > 0)
            {
                if (attribute.ConstructorArguments[0].Value is INamedTypeSymbol sourceType)
                {
                    mapFromAttributes.Add(sourceType);
                }
            }
            else if (attribute.AttributeClass?.Name == "MapToAttribute" &&
                     attribute.ConstructorArguments.Length > 0)
            {
                if (attribute.ConstructorArguments[0].Value is INamedTypeSymbol targetType)
                {
                    mapToAttributes.Add(targetType);
                }
            }
        }

        if (mapFromAttributes.Count == 0 && mapToAttributes.Count == 0)
            return null;

        return new ClassToGenerate(
            classSymbol,
            mapFromAttributes,
            mapToAttributes,
            GetPropertyMappings(classSymbol));
    }

    private static Dictionary<string, PropertyMapping> GetPropertyMappings(INamedTypeSymbol classSymbol)
    {
        var mappings = new Dictionary<string, PropertyMapping>();

        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var mapPropertyAttr = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "MapPropertyAttribute");

            if (mapPropertyAttr != null)
            {
                var ignore = false;
                string? sourcePropertyName = null;

                foreach (var namedArg in mapPropertyAttr.NamedArguments)
                {
                    if (namedArg.Key == "Ignore" && namedArg.Value.Value is bool ignoreValue)
                    {
                        ignore = ignoreValue;
                    }
                }

                if (mapPropertyAttr.ConstructorArguments.Length > 0 &&
                    mapPropertyAttr.ConstructorArguments[0].Value is string sourceName)
                {
                    sourcePropertyName = sourceName;
                }

                mappings[member.Name] = new PropertyMapping(member.Name, member.Type, sourcePropertyName, ignore);
            }
            else
            {
                mappings[member.Name] = new PropertyMapping(member.Name, member.Type, null, false);
            }
        }

        return mappings;
    }

    private static void Execute(ClassToGenerate? classToGenerate, SourceProductionContext context)
    {
        if (classToGenerate == null)
            return;

        var source = GenerateMappingCode(classToGenerate);
        context.AddSource($"{classToGenerate.ClassSymbol.Name}_Mappings.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateMappingCode(ClassToGenerate classToGenerate)
    {
        var sb = new StringBuilder();
        var className = classToGenerate.ClassSymbol.Name;
        var namespaceName = classToGenerate.ClassSymbol.ContainingNamespace.ToDisplayString();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System.Linq;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        // Generate MapFrom methods
        foreach (var sourceType in classToGenerate.MapFromTypes)
        {
            GenerateMapFromMethod(sb, classToGenerate.ClassSymbol, sourceType, classToGenerate.PropertyMappings);
        }

        // Generate MapTo methods
        foreach (var targetType in classToGenerate.MapToTypes)
        {
            GenerateMapToMethod(sb, classToGenerate.ClassSymbol, targetType, classToGenerate.PropertyMappings);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateMapFromMethod(
        StringBuilder sb,
        INamedTypeSymbol targetClassSymbol,
        INamedTypeSymbol sourceType,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        var className = targetClassSymbol.Name;
        var sourceTypeName = sourceType.ToDisplayString();

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps from <see cref=\"{sourceTypeName}\"/> to this instance.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static {className} MapFrom({sourceTypeName} source)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (source == null) throw new System.ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine($"            return new {className}");
        sb.AppendLine("            {");

        var sourceProperties = sourceType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.GetMethod != null)
            .ToDictionary(p => p.Name, p => p);

        var mappedProperties = new List<string>();

        foreach (var mapping in propertyMappings.Values)
        {
            if (mapping.Ignore)
                continue;

            var sourcePropName = mapping.SourcePropertyName ?? mapping.PropertyName;
            
            if (!sourceProperties.TryGetValue(sourcePropName, out var sourceProperty))
                continue; // Auto-ignore: property not found in source

            var mappingExpression = GetMappingExpression(
                $"source.{sourcePropName}",
                sourceProperty.Type,
                mapping.PropertyType,
                isMapFrom: true);

            if (mappingExpression != null)
            {
                mappedProperties.Add($"                {mapping.PropertyName} = {mappingExpression}");
            }
        }

        sb.AppendLine(string.Join(",\n", mappedProperties));
        sb.AppendLine("            };");
        sb.AppendLine("        }");

        // Generate list mapping extension method
        GenerateListMapFromMethod(sb, className, sourceType);
    }

    private static void GenerateMapToMethod(
        StringBuilder sb,
        INamedTypeSymbol sourceClassSymbol,
        INamedTypeSymbol targetType,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        var className = sourceClassSymbol.Name;
        var targetTypeName = targetType.ToDisplayString();

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps this instance to <see cref=\"{targetTypeName}\"/>.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public {targetTypeName} MapTo()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {targetTypeName}");
        sb.AppendLine("            {");

        var targetProperties = targetType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.SetMethod != null)
            .ToDictionary(p => p.Name, p => p);

        var mappedProperties = new List<string>();

        foreach (var mapping in propertyMappings.Values)
        {
            if (mapping.Ignore)
                continue;

            var targetPropName = mapping.SourcePropertyName ?? mapping.PropertyName;
            
            if (!targetProperties.TryGetValue(targetPropName, out var targetProperty))
                continue; // Auto-ignore: property not found in target

            var mappingExpression = GetMappingExpression(
                $"this.{mapping.PropertyName}",
                mapping.PropertyType,
                targetProperty.Type,
                isMapFrom: false);

            if (mappingExpression != null)
            {
                mappedProperties.Add($"                {targetPropName} = {mappingExpression}");
            }
        }

        sb.AppendLine(string.Join(",\n", mappedProperties));
        sb.AppendLine("            };");
        sb.AppendLine("        }");

        // Generate list mapping extension method
        GenerateListMapToMethod(sb, className, targetType);
    }

    private static string? GetMappingExpression(
        string sourceExpression,
        ITypeSymbol sourceType,
        ITypeSymbol targetType,
        bool isMapFrom)
    {
        // Get underlying types if nullable reference types
        var unwrappedSourceType = GetUnwrappedType(sourceType);
        var unwrappedTargetType = GetUnwrappedType(targetType);
        var isSourceNullable = IsNullableType(sourceType);

        // Check if types are directly assignable
        if (SymbolEqualityComparer.Default.Equals(unwrappedSourceType, unwrappedTargetType) || 
            IsImplicitlyConvertible(unwrappedSourceType, unwrappedTargetType))
        {
            return sourceExpression;
        }

        // Check for collection types (List<T>, IEnumerable<T>, ICollection<T>, etc.)
        var sourceElementType = GetCollectionElementType(unwrappedSourceType);
        var targetElementType = GetCollectionElementType(unwrappedTargetType);

        if (sourceElementType != null && targetElementType != null)
        {
            return GenerateCollectionMapping(sourceExpression, sourceElementType, targetElementType, unwrappedTargetType, isMapFrom);
        }

        // Check for nested mapping (complex types with MapFrom/MapTo attributes)
        if (isMapFrom)
        {
            if (HasMapFromAttribute(unwrappedTargetType, unwrappedSourceType))
            {
                // Get the non-nullable type name for calling static methods
                var targetTypeName = GetTypeNameWithoutNullable(unwrappedTargetType);
                
                if (isSourceNullable)
                {
                    return $"{sourceExpression} != null ? {targetTypeName}.MapFrom({sourceExpression}) : null";
                }
                return $"{targetTypeName}.MapFrom({sourceExpression})";
            }
        }
        else
        {
            if (HasMapToMethod(unwrappedSourceType, unwrappedTargetType))
            {
                if (isSourceNullable)
                {
                    return $"{sourceExpression}?.MapTo()";
                }
                return $"{sourceExpression}.MapTo()";
            }
        }

        // Fallback: direct assignment if types seem compatible
        if (AreTypesCompatible(unwrappedSourceType, unwrappedTargetType))
        {
            return sourceExpression;
        }

        return null;
    }
    
    private static ITypeSymbol GetUnwrappedType(ITypeSymbol type)
    {
        // Handle Nullable<T>
        if (type is INamedTypeSymbol namedType && 
            namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return namedType.TypeArguments[0];
        }
        
        // For reference types with nullable annotation, return the original type
        // as the underlying type is the same
        return type;
    }

    private static bool IsNullableType(ITypeSymbol type)
    {
        // Check nullable reference type annotation
        if (type.NullableAnnotation == NullableAnnotation.Annotated)
            return true;
        
        // Check Nullable<T>
        if (type is INamedTypeSymbol namedType && 
            namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
            return true;
        
        return false;
    }

    private static string? GenerateCollectionMapping(
        string sourceExpression,
        ITypeSymbol sourceElementType,
        ITypeSymbol targetElementType,
        ITypeSymbol targetCollectionType,
        bool isMapFrom)
    {
        var unwrappedSourceElement = GetUnwrappedType(sourceElementType);
        var unwrappedTargetElement = GetUnwrappedType(targetElementType);
        
        string elementMapping;

        // Check if element types are the same
        if (SymbolEqualityComparer.Default.Equals(unwrappedSourceElement, unwrappedTargetElement) ||
            unwrappedSourceElement.ToDisplayString() == unwrappedTargetElement.ToDisplayString())
        {
            elementMapping = "x";
        }
        // Check for nested mapping on collection elements
        else if (isMapFrom && HasMapFromAttribute(unwrappedTargetElement, unwrappedSourceElement))
        {
            // Get the non-nullable type name for calling static methods
            var targetElementTypeName = GetTypeNameWithoutNullable(unwrappedTargetElement);
            elementMapping = $"{targetElementTypeName}.MapFrom(x)";
        }
        else if (!isMapFrom && HasMapToMethod(unwrappedSourceElement, unwrappedTargetElement))
        {
            elementMapping = "x.MapTo()";
        }
        else if (AreTypesCompatible(unwrappedSourceElement, unwrappedTargetElement))
        {
            elementMapping = "x";
        }
        else
        {
            // Types don't match - skip mapping
            return null;
        }

        // Determine the target collection type
        var targetTypeString = targetCollectionType.ToDisplayString();
        var selectExpression = $"{sourceExpression}?.Select(x => {elementMapping})";

        if (targetTypeString.StartsWith("System.Collections.Generic.List<") || 
            targetTypeString.Contains("List<"))
        {
            return $"{selectExpression}?.ToList()";
        }
        if (targetTypeString.Contains("[]"))
        {
            return $"{selectExpression}?.ToArray()";
        }
        if (targetTypeString.StartsWith("System.Collections.Generic.IList<") ||
            targetTypeString.StartsWith("System.Collections.Generic.ICollection<"))
        {
            return $"{selectExpression}?.ToList()";
        }
        
        // Default to enumerable
        return selectExpression;
    }

    private static ITypeSymbol? GetCollectionElementType(ITypeSymbol type)
    {
        // Handle arrays
        if (type is IArrayTypeSymbol arrayType)
        {
            return arrayType.ElementType;
        }

        // Handle generic collections
        if (type is INamedTypeSymbol namedType)
        {
            // Check if it's a generic type
            if (namedType.IsGenericType)
            {
                var typeDefinition = namedType.ConstructedFrom?.ToDisplayString() ?? "";
                
                // Common collection interfaces and types
                if (typeDefinition.Contains("IEnumerable<") ||
                    typeDefinition.Contains("ICollection<") ||
                    typeDefinition.Contains("IList<") ||
                    typeDefinition.Contains("List<") ||
                    typeDefinition.Contains("IReadOnlyList<") ||
                    typeDefinition.Contains("IReadOnlyCollection<") ||
                    typeDefinition.Contains("HashSet<") ||
                    typeDefinition.Contains("ISet<"))
                {
                    return namedType.TypeArguments.FirstOrDefault();
                }
            }

            // Check interfaces for IEnumerable<T>
            foreach (var iface in namedType.AllInterfaces)
            {
                if (iface.IsGenericType && 
                    iface.ConstructedFrom.ToDisplayString().Contains("IEnumerable<"))
                {
                    return iface.TypeArguments.FirstOrDefault();
                }
            }
        }

        return null;
    }

    private static bool HasMapFromAttribute(ITypeSymbol targetType, ITypeSymbol sourceType)
    {
        // Get the underlying named type symbol (handles nullable reference types)
        var namedTargetType = GetNamedTypeSymbol(targetType);
        if (namedTargetType == null)
            return false;

        var unwrappedSource = GetUnwrappedType(sourceType);
        var namedSourceType = GetNamedTypeSymbol(unwrappedSource);
        if (namedSourceType == null)
            return false;
            
        var sourceTypeName = namedSourceType.ToDisplayString();

        foreach (var attr in namedTargetType.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "MapFromAttribute" &&
                attr.ConstructorArguments.Length > 0 &&
                attr.ConstructorArguments[0].Value is INamedTypeSymbol attrSourceType)
            {
                // Compare by display string for more reliable matching
                var attrSourceTypeName = attrSourceType.ToDisplayString();
                if (attrSourceTypeName == sourceTypeName)
                {
                    return true;
                }
                
                // Also try symbol comparison
                if (SymbolEqualityComparer.Default.Equals(attrSourceType, namedSourceType))
                {
                    return true;
                }
            }
        }

        return false;
    }
    
    private static INamedTypeSymbol? GetNamedTypeSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol namedType)
        {
            // For Nullable<T>, get the underlying type
            if (namedType.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
            {
                return namedType.TypeArguments[0] as INamedTypeSymbol;
            }
            // Return the original type without nullable annotation
            return namedType.OriginalDefinition.Equals(namedType, SymbolEqualityComparer.Default) 
                ? namedType 
                : namedType;
        }
        return null;
    }
    
    private static string GetTypeNameWithoutNullable(ITypeSymbol type)
    {
        var namedType = GetNamedTypeSymbol(type);
        if (namedType == null)
            return type.ToDisplayString();
        
        // Use a display format that excludes nullable reference type annotations
        return namedType.ToDisplayString(new SymbolDisplayFormat(
            globalNamespaceStyle: SymbolDisplayGlobalNamespaceStyle.Omitted,
            typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces,
            genericsOptions: SymbolDisplayGenericsOptions.IncludeTypeParameters,
            miscellaneousOptions: SymbolDisplayMiscellaneousOptions.None
        ));
    }

    private static bool HasMapToMethod(ITypeSymbol sourceType, ITypeSymbol targetType)
    {
        // Get the underlying named type symbol (handles nullable reference types)
        var namedSourceType = GetNamedTypeSymbol(sourceType);
        if (namedSourceType == null)
            return false;

        var unwrappedTarget = GetUnwrappedType(targetType);
        var namedTargetType = GetNamedTypeSymbol(unwrappedTarget);
        if (namedTargetType == null)
            return false;
            
        var targetTypeName = namedTargetType.ToDisplayString();

        foreach (var attr in namedSourceType.GetAttributes())
        {
            if (attr.AttributeClass?.Name == "MapToAttribute" &&
                attr.ConstructorArguments.Length > 0 &&
                attr.ConstructorArguments[0].Value is INamedTypeSymbol attrTargetType)
            {
                // Compare by display string for more reliable matching
                var attrTargetTypeName = attrTargetType.ToDisplayString();
                if (attrTargetTypeName == targetTypeName)
                {
                    return true;
                }
                
                // Also try symbol comparison
                if (SymbolEqualityComparer.Default.Equals(attrTargetType, namedTargetType))
                {
                    return true;
                }
            }
        }

        return false;
    }

    private static bool IsImplicitlyConvertible(ITypeSymbol source, ITypeSymbol target)
    {
        // Only check special types (primitives, string, etc.) - not custom classes
        // SpecialType.None means it's a custom type, so we can't assume implicit conversion
        if (source.SpecialType == SpecialType.None || target.SpecialType == SpecialType.None)
            return false;
            
        // Same special types are convertible (e.g., string to string)
        if (source.SpecialType == target.SpecialType)
            return true;

        // int -> long, float -> double, etc.
        var numericTypes = new[]
        {
            SpecialType.System_Byte, SpecialType.System_SByte,
            SpecialType.System_Int16, SpecialType.System_UInt16,
            SpecialType.System_Int32, SpecialType.System_UInt32,
            SpecialType.System_Int64, SpecialType.System_UInt64,
            SpecialType.System_Single, SpecialType.System_Double,
            SpecialType.System_Decimal
        };

        return numericTypes.Contains(source.SpecialType) && numericTypes.Contains(target.SpecialType);
    }

    private static bool AreTypesCompatible(ITypeSymbol source, ITypeSymbol target)
    {
        // Check for exact match
        if (SymbolEqualityComparer.Default.Equals(source, target))
            return true;

        // Check if target is assignable from source (inheritance/interface)
        if (source is INamedTypeSymbol namedSource && target is INamedTypeSymbol namedTarget)
        {
            // Check base types
            var currentBase = namedSource.BaseType;
            while (currentBase != null)
            {
                if (SymbolEqualityComparer.Default.Equals(currentBase, namedTarget))
                    return true;
                currentBase = currentBase.BaseType;
            }

            // Check interfaces
            if (namedSource.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, namedTarget)))
                return true;
        }

        return false;
    }

    private static void GenerateListMapFromMethod(StringBuilder sb, string className, INamedTypeSymbol sourceType)
    {
        var sourceTypeName = sourceType.ToDisplayString();

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps a collection of <see cref=\"{sourceTypeName}\"/> to a list of {className}.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static System.Collections.Generic.List<{className}> MapFrom(System.Collections.Generic.IEnumerable<{sourceTypeName}>? sources)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sources == null) return new System.Collections.Generic.List<" + className + ">();");
        sb.AppendLine($"            return sources.Select(MapFrom).ToList();");
        sb.AppendLine("        }");
    }

    private static void GenerateListMapToMethod(StringBuilder sb, string className, INamedTypeSymbol targetType)
    {
        var targetTypeName = targetType.ToDisplayString();

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps a collection of {className} to a list of <see cref=\"{targetTypeName}\"/>.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static System.Collections.Generic.List<{targetTypeName}> MapTo(System.Collections.Generic.IEnumerable<{className}>? sources)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (sources == null) return new System.Collections.Generic.List<" + targetTypeName + ">();");
        sb.AppendLine($"            return sources.Select(x => x.MapTo()).ToList();");
        sb.AppendLine("        }");
    }

    private class ClassToGenerate(
        INamedTypeSymbol classSymbol,
        List<INamedTypeSymbol> mapFromTypes,
        List<INamedTypeSymbol> mapToTypes,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        public INamedTypeSymbol ClassSymbol { get; } = classSymbol;
        public List<INamedTypeSymbol> MapFromTypes { get; } = mapFromTypes;
        public List<INamedTypeSymbol> MapToTypes { get; } = mapToTypes;
        public Dictionary<string, PropertyMapping> PropertyMappings { get; } = propertyMappings;
    }

    private class PropertyMapping(string propertyName, ITypeSymbol propertyType, string? sourcePropertyName, bool ignore)
    {
        public string PropertyName { get; } = propertyName;
        public ITypeSymbol PropertyType { get; } = propertyType;
        public string? SourcePropertyName { get; } = sourcePropertyName;
        public bool Ignore { get; } = ignore;
    }
}
