#nullable enable
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MapSharp.SourceGenerator;

[Generator]
public class MapperGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with MapFrom or MapTo attributes
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsCandidateClass(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Generate the mapping code
        context.RegisterSourceOutput(classDeclarations, static (spc, source) => Execute(source, spc));
    }

    private static bool IsCandidateClass(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration &&
               classDeclaration.AttributeLists.Count > 0;
    }

    private static ClassToGenerate? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration);

        if (classSymbol == null)
            return null;

        var mapFromAttributes = new List<INamedTypeSymbol>();
        var mapToAttributes = new List<INamedTypeSymbol>();

        foreach (var attribute in classSymbol.GetAttributes())
        {
            if (attribute.AttributeClass?.Name == "MapFromAttribute" &&
                attribute.ConstructorArguments.Length > 0)
            {
                if (attribute.ConstructorArguments[0].Value is INamedTypeSymbol sourceType)
                {
                    mapFromAttributes.Add(sourceType);
                }
            }
            else if (attribute.AttributeClass?.Name == "MapToAttribute" &&
                     attribute.ConstructorArguments.Length > 0)
            {
                if (attribute.ConstructorArguments[0].Value is INamedTypeSymbol targetType)
                {
                    mapToAttributes.Add(targetType);
                }
            }
        }

        if (mapFromAttributes.Count == 0 && mapToAttributes.Count == 0)
            return null;

        return new ClassToGenerate(
            classSymbol,
            mapFromAttributes,
            mapToAttributes,
            GetPropertyMappings(classSymbol));
    }

    private static Dictionary<string, PropertyMapping> GetPropertyMappings(INamedTypeSymbol classSymbol)
    {
        var mappings = new Dictionary<string, PropertyMapping>();

        foreach (var member in classSymbol.GetMembers().OfType<IPropertySymbol>())
        {
            var mapPropertyAttr = member.GetAttributes()
                .FirstOrDefault(a => a.AttributeClass?.Name == "MapPropertyAttribute");

            if (mapPropertyAttr != null)
            {
                var ignore = false;
                string? sourcePropertyName = null;

                foreach (var namedArg in mapPropertyAttr.NamedArguments)
                {
                    if (namedArg.Key == "Ignore" && namedArg.Value.Value is bool ignoreValue)
                    {
                        ignore = ignoreValue;
                    }
                }

                if (mapPropertyAttr.ConstructorArguments.Length > 0 &&
                    mapPropertyAttr.ConstructorArguments[0].Value is string sourceName)
                {
                    sourcePropertyName = sourceName;
                }

                mappings[member.Name] = new PropertyMapping(member.Name, sourcePropertyName, ignore);
            }
            else
            {
                mappings[member.Name] = new PropertyMapping(member.Name, null, false);
            }
        }

        return mappings;
    }

    private static void Execute(ClassToGenerate? classToGenerate, SourceProductionContext context)
    {
        if (classToGenerate == null)
            return;

        var source = GenerateMappingCode(classToGenerate);
        context.AddSource($"{classToGenerate.ClassSymbol.Name}_Mappings.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GenerateMappingCode(ClassToGenerate classToGenerate)
    {
        var sb = new StringBuilder();
        var className = classToGenerate.ClassSymbol.Name;
        var namespaceName = classToGenerate.ClassSymbol.ContainingNamespace.ToDisplayString();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName}");
        sb.AppendLine("{");
        sb.AppendLine($"    public partial class {className}");
        sb.AppendLine("    {");

        // Generate MapFrom methods
        foreach (var sourceType in classToGenerate.MapFromTypes)
        {
            GenerateMapFromMethod(sb, className, sourceType, classToGenerate.PropertyMappings);
        }

        // Generate MapTo methods
        foreach (var targetType in classToGenerate.MapToTypes)
        {
            GenerateMapToMethod(sb, className, targetType, classToGenerate.PropertyMappings);
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void GenerateMapFromMethod(
        StringBuilder sb,
        string className,
        INamedTypeSymbol sourceType,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        var sourceTypeName = sourceType.ToDisplayString();
        var sourceTypeShortName = sourceType.Name;

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps from <see cref=\"{sourceTypeName}\"/> to this instance.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public static {className} MapFrom({sourceTypeName} source)");
        sb.AppendLine("        {");
        sb.AppendLine($"            if (source == null) throw new System.ArgumentNullException(nameof(source));");
        sb.AppendLine();
        sb.AppendLine($"            return new {className}");
        sb.AppendLine("            {");

        var sourceProperties = sourceType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                       p.GetMethod != null)
            .ToList();

        var mappedProperties = new List<string>();

        foreach (var mapping in propertyMappings.Values)
        {
            if (mapping.Ignore)
                continue;

            var sourcePropName = mapping.SourcePropertyName ?? mapping.PropertyName;
            var sourceProperty = sourceProperties.FirstOrDefault(p => p.Name == sourcePropName);

            if (sourceProperty != null)
            {
                mappedProperties.Add($"                {mapping.PropertyName} = source.{sourcePropName}");
            }
        }

        sb.AppendLine(string.Join(",\n", mappedProperties));
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private static void GenerateMapToMethod(
        StringBuilder sb,
        string className,
        INamedTypeSymbol targetType,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        var targetTypeName = targetType.ToDisplayString();

        sb.AppendLine();
        sb.AppendLine($"        /// <summary>");
        sb.AppendLine($"        /// Maps this instance to <see cref=\"{targetTypeName}\"/>.");
        sb.AppendLine($"        /// </summary>");
        sb.AppendLine($"        public {targetTypeName} MapTo()");
        sb.AppendLine("        {");
        sb.AppendLine($"            return new {targetTypeName}");
        sb.AppendLine("            {");

        var targetProperties = targetType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(p => p.DeclaredAccessibility == Accessibility.Public &&
                       p.SetMethod != null)
            .ToList();

        var mappedProperties = new List<string>();

        foreach (var mapping in propertyMappings.Values)
        {
            if (mapping.Ignore)
                continue;

            var targetPropName = mapping.SourcePropertyName ?? mapping.PropertyName;
            var targetProperty = targetProperties.FirstOrDefault(p => p.Name == targetPropName);

            if (targetProperty != null)
            {
                mappedProperties.Add($"                {targetPropName} = this.{mapping.PropertyName}");
            }
        }

        sb.AppendLine(string.Join(",\n", mappedProperties));
        sb.AppendLine("            };");
        sb.AppendLine("        }");
    }

    private class ClassToGenerate(
        INamedTypeSymbol classSymbol,
        List<INamedTypeSymbol> mapFromTypes,
        List<INamedTypeSymbol> mapToTypes,
        Dictionary<string, PropertyMapping> propertyMappings)
    {
        public INamedTypeSymbol ClassSymbol { get; } = classSymbol;
        public List<INamedTypeSymbol> MapFromTypes { get; } = mapFromTypes;
        public List<INamedTypeSymbol> MapToTypes { get; } = mapToTypes;
        public Dictionary<string, PropertyMapping> PropertyMappings { get; } = propertyMappings;
    }

    private class PropertyMapping(string propertyName, string? sourcePropertyName, bool ignore)
    {
        public string PropertyName { get; } = propertyName;
        public string? SourcePropertyName { get; } = sourcePropertyName;
        public bool Ignore { get; } = ignore;
    }
}

